id: IF86F311B
ocr_import_info:
  timestamp: '2023-10-06T09:40:01.405771+00:00'
  batch_id: batch-f3bc
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharmakyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-10-06 10:51:09.893455+00:00
last_modified: 2023-10-06 10:51:09.893464+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1NLM150
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1NLM150
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བླ་མ་མཆོད་པའི་ཆོ་ག་སོགས།
  languages:
  - bo
  author: པཎ་ཆེན་བློ་བཟང་ཆོས་ཀྱི་རྒྱལ་མཚན།
statistics:
  ocr_word_mean_confidence_index: 0.9499171406447926
  ocr_word_median_confidence_index: 0.9981
bases:
  I1NLM150_001:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1NLM150_001
      total_pages: 252
      volume_number: 1
      volume_pages_bdrc_intro: 0
    order: 1
    base_file: I1NLM150_001.txt
    statistics:
      ocr_word_median_confidence_index: 0.9981
      ocr_word_mean_confidence_index: 0.9499171406447926
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
